OAFS optional, adds 10KB, lol

diff --git a/orwin b/orwin
--- a/orwin
+++ b/orwin
@@ -64,12 +64,21 @@ rm fil
 
 echo > orwin.reg
 
-( cl65 -r -Oirs -C atmos.cfg $* $OPTS '-D__AUTORUN__=$C7' -t atmos $name.c app_*.c -o $name.tap -vm -m $name.map 2>&1 | sed 's/(\([0-9]\+\))/:\1/g' ) || (echo "??????????????? FAILED ???????????"; exit 72)
+
+
+# TODO: ------------ ADDS 10KB !!!! LOL-FULL!
+
+#export OAFS="-DOAFS oafs.c"
+
+export OAFS=""
+
+
+( cl65 -r -Oirs -C atmos.cfg $* $OPTS '-D__AUTORUN__=$C7' -t atmos $OAFS $name.c app_*.c -o $name.tap -vm -m $name.map 2>&1 | sed 's/(\([0-9]\+\))/:\1/g' ) || (echo "??????????????? FAILED ???????????"; exit 72)
 echo
 perl mapsizes.pl < orwin.map > orwin.reg
 #cat orwin.reg
 echo
-( cl65 -r -Oirs -C atmos.cfg $* $OPTS '-D__AUTORUN__=$C7' -t atmos $name.c app_*.c -o $name.tap -vm -m $name.map 2>&1 | sed 's/(\([0-9]\+\))/:\1/g' ) || (echo "??????????????? FAILED ???????????"; exit 72)
+( cl65 -r -Oirs -C atmos.cfg $* $OPTS '-D__AUTORUN__=$C7' -t atmos $OAFS $name.c app_*.c -o $name.tap -vm -m $name.map 2>&1 | sed 's/(\([0-9]\+\))/:\1/g' ) || (echo "??????????????? FAILED ???????????"; exit 72)
 
 echo
 cat orwin.reg
